name: "Main branch Bench"

on:
  push:
    branches: master

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.filter.outputs.watches }}
    steps:
      - uses: actions/checkout@v5
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            watches:
              - 'zkml/**'
              - 'mpcs/**'
              - '.github/workflows/main-bench.yml'

  benchmark_pr_branch:
    name: Continuous Benchmarking PRs with Bencher
    needs: changes
    if: ${{ needs.changes.outputs.should_run == 'true' }}
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: "recursive"
      - name: Install protoc via apt
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - name: Install the Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
          # Manually configure rust-cache
          cache: false
      - uses: bencherdev/bencher@main
      - name: Track PR Benchmarks with Bencher
        run: |
          cd zkml && \
          bencher run \
          --project deep-prove-f264508-ok338l62t85v1 \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch main \
          --threshold-measure latency \
          --threshold-test percentage \
          --threshold-upper-boundary 0.20 \
          --thresholds-reset \
          --testbed ci-runner \
          --err \
          --adapter rust_criterion \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          "cargo bench"

